Repository EveryAnalytics/web-analytics-handbook, pull requests merged in 2021-08, with the labels that each got.

#9 Add deploy workflow
  .github/workflows/deploy.yml
  docusaurus.config.js
Labels: help wanted

#13 Feature/12
  babel.config.js
  package.json
  src/components/HomepageFeatures.module.css
  src/components/HomepageFeatures.tsx
  src/theme/mq.ts
  tsconfig.json
  yarn.lock
Labels: good first issue

#14 GitHub PR 템플릿 추가
  .github/pull_request_template.md
Labels: enhancement

#24 [용어사전] 최소한의 ui-kit 구현
  src/components/WikiTable/WikiTable.tsx
  src/components/WikiTable/WikiTableRow.tsx
  src/components/WikiTable/index.ts
  src/pages/wiki/index.js
  src/types/WikiWord.ts
  src/types/index.ts
  tsconfig.json
  wiki.json
Labels: enhancement, 용어집

#32 용어사전 테이블 페이지네이션 기능 구현
  src/components/WikiTable/WikiTable.tsx
  src/hooks/usePagination.ts
  wiki.json
Labels: 용어집

#39 Feature/28
  babel.config.js
  package.json
  src/components/HomepageFeatures.tsx
  src/pages/index.js
  tsconfig.json
  yarn.lock
Labels: 용어집

#44 notion에 있는 용어 data 추가
  wiki.json
Labels: 용어집

#49 eslint 세팅
  .eslintignore
  .eslintrc.json
  package.json
  yarn.lock
Labels: 용어집

#51 prettier 설정
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  yarn.lock
Labels: 용어집

#57 docs: add document about abtest basic
  docs/handbook/ab-test.md
  docs/handbook/tutorial-basics/_category_.json
  docs/handbook/tutorial-extras/_category_.json
Labels: 핸드북

#60 Update README - 구성, 용어 네이밍규칙 추가
  README.md
Labels: 용어집

#59 디자인 UI 및 레이아웃 수정
  .eslintrc.json
  package.json
  src/components/WikiSearch/SearchFilter.tsx
  src/components/WikiSearch/SearchInput.tsx
  src/components/WikiSearch/index.tsx
  src/components/WikiTable/WikiTable.tsx
  src/css/custom.css
  src/pages/wiki/index.js
  static/searchLetter.ts
  yarn.lock
Labels: 용어집

#64 feat/38 why-ga 블로그 글 작성
  blog/2019-05-28-hola.md
  blog/2019-05-30-welcome.md
  blog/2021-08-22-why-ga.md
Labels: 블로그

#68 doc/66: ga-url-fragmentation issue 블로그 작성
  blog/2021-08-22-ga-url-fragmentation-issue.md
Labels: 블로그

#73 doc/66 비어있는 author_title 항목값 삭제
  blog/2021-08-22-ga-url-fragmentation-issue.md
Labels: bug

#69 docs: add handbook about amplitude
  docs/handbook/amplitude-basics/_category_.json
  docs/handbook/amplitude-basics/browse-charts.md
  docs/handbook/amplitude-basics/congratulations.md
  docs/handbook/amplitude-basics/dashboard.md
  docs/handbook/amplitude-basics/user-activity.md
  docs/handbook/amplitude-basics/what-is-amplitude.md
Labels: 📚 핸드북

#98 [DOCS] GA 기본 3.2 acquisition reports
  docs/handbook/google-analytics-basics/_category_.json
  docs/handbook/google-analytics-basics/acquisition-reports.md
Labels: 📚 핸드북

#96 docs: GA 목표 핸드북 작성
  docs/handbook/google-analytics-basics/goals.md
Labels: 📚 핸드북

#45 [DOCS] 웹에서 어떤 데이터추적-블로그
  docs/handbook/which-data-should-be-tracked/blog.md
Labels: 📚 핸드북

#63 DOCS: 퍼널분석 핸드북 작성
  docs/handbook/funnel-analysis.md
  docs/handbook/tutorial-basics/_category_.json
  docs/handbook/tutorial-extras/_category_.json
  docs/handbook/tutorial-extras/which-data-should-be-tracked-blog.md
Labels: 📚 핸드북

#67 GoogleAnalytics 기본
  docs/handbook/google-analytics-basics/ga-basic.md
Labels: 📚 핸드북

#108 [Feature/107] 용어사전 추가 (소스, 매체), 톤 정리
  wiki.json
Labels: 📖 용어집

#114 doc: 용어 몇개 추가
  wiki.json
Labels: 📖 용어집

#93 doc/88 : README 꾸미기
  README.md
Labels: 📖 documentation

#110 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 📖 documentation
