Repository EveryAnalytics/web-analytics-handbook, pull requests merged in 2021-09, with the labels that each got.

#105 Contributing.md 파일 생성
  CONTRIBUTING.md
Labels: 📖 documentation

#115 Docs: 핸드북 GA - 잠재고객 보고서 md 파일 생성
  docs/handbook/google-analytics-basics/audience-reports.md
Labels: 📚 핸드북

#65 용어사전 검색 및 필터 기능 구현
  src/components/WikiSearch/LetterButtonList.tsx
  src/components/WikiSearch/LetterFilter.tsx
  src/components/WikiSearch/SearchInput.tsx
  src/components/WikiSearch/index.tsx
  src/components/WikiTable/WikiTable.tsx
  src/hooks/usePagination.ts
  src/hooks/useSearch.ts
  src/pages/wiki/index.js
  static/korean-consonants.ts
Labels: 📖 용어집

#104 docs: GA Google Ads 핸드북 작성
  docs/handbook/google-analytics-basics/google-ads.md
Labels: 📚 핸드북

#126 docs: add handbook intro
  docs/handbook/intro.md
Labels: 📖 documentation, 📚 핸드북

#124 bug/123: Fix filter btn color
  src/components/WikiSearch/LetterButtonList.tsx
Labels: 🐛 bug

#129 docs: Add article about flutter plugin analytics problem in blog
  blog/2021-09-04-flutter-fb-analytics-plugin.md
  docusaurus.config.js
Labels: 👾 블로그

#142 docs: GA Basic 3.3 Behavior reports
  docs/handbook/google-analytics-basics/behavior-reports.md
Labels: 📚 핸드북

#138 핸드북 챕터 3~4 템플릿 적용(3.3 제외)
  docs/handbook/google-analytics-basics/acquisition-reports.md
  docs/handbook/google-analytics-basics/audience-reports.md
  docs/handbook/google-analytics-basics/goals.md
  docs/handbook/google-analytics-basics/google-ads.md
Labels: 📚 핸드북

#134 docs:GA 데이터 수집 관련 글 작성 완성 (GA 고급 1.1 동영상 정리)
  docs/handbook/google-analytics-basics/how-to-collect-data.md
Labels: 📚 핸드북

#139 docs:amplitude 차트 종류 정리
  docs/handbook/amplitude-basics/amplitude-chart.md
Labels: 📖 documentation

#111 docs: add issue_template
  .github/bug_report_issue_template.md
  .github/content_issue_template.md
  .github/feature_request_issue_template.md
  docs/handbook/google-analytics-basics/how-to-track-a-maketing-campaign.md
  docs/handbook/google-analytics-basics/tracking-campaigns-with-URL-Builder.md
Labels: 📖 documentation

#135 docs: GA 고급 정리 1.2
  docs/handbook/google-analytics-basics/categorizing-data-into-users-and-sessions.md
Labels: 📖 documentation

#145 [DOCS] Add Handbook index
  docs/handbook/Amplitude/01-Settings/amplitude-setting.md
  docs/handbook/Amplitude/02-Basics/amplitude-chart.md
  docs/handbook/Amplitude/02-Basics/browse-charts.md
  docs/handbook/Amplitude/02-Basics/congratulations.md
  docs/handbook/Amplitude/02-Basics/dashboard.md
  docs/handbook/Amplitude/02-Basics/user-activity.md
  docs/handbook/Amplitude/02-Basics/what-is-amplitude.md
  docs/handbook/Amplitude/03-Advanced/amplitude-advanced.md
  docs/handbook/Amplitude/_category_.json
  docs/handbook/Google-Analytics/01-Settings/01-GA-hierarchy.md
  docs/handbook/Google-Analytics/01-Settings/02-population-poll.md
  docs/handbook/Google-Analytics/01-Settings/03-GA-ads.md
  docs/handbook/Google-Analytics/01-Settings/04-search-console.md
  docs/handbook/Google-Analytics/01-Settings/05-filter.md
  docs/handbook/Google-Analytics/01-Settings/google-ads.md
  docs/handbook/Google-Analytics/02-Basics/01-reports.md
  docs/handbook/Google-Analytics/02-Basics/02-ABC-framework.md
  docs/handbook/Google-Analytics/02-Basics/03-reports-advanced.md
  docs/handbook/Google-Analytics/02-Basics/04-setting-goals.md
  docs/handbook/Google-Analytics/02-Basics/05-event-tagging.md
  docs/handbook/Google-Analytics/02-Basics/06-online-transaction.md
  docs/handbook/Google-Analytics/02-Basics/acquisition-reports.md
  docs/handbook/Google-Analytics/02-Basics/audience-reports.md
  docs/handbook/Google-Analytics/02-Basics/behavior-reports.md
  docs/handbook/Google-Analytics/02-Basics/goals.md
  docs/handbook/Google-Analytics/02-Basics/how-to-collect-data.md
  docs/handbook/Google-Analytics/02-Basics/introduce.md
  docs/handbook/Google-Analytics/02-Basics/ua-ga4-difference.md
  docs/handbook/Google-Analytics/03-Advanced/01-terms.md
  docs/handbook/Google-Analytics/03-Advanced/02-acquisition.md
  docs/handbook/Google-Analytics/03-Advanced/03-behavior.md
  docs/handbook/Google-Analytics/03-Advanced/04-conversion.md
  docs/handbook/Google-Analytics/03-Advanced/ab-test.md
  docs/handbook/Google-Analytics/03-Advanced/funnel-analysis.md
  docs/handbook/Google-Analytics/_category_.json
  docs/handbook/Introduction/01-importance-of-data-analysis.md
  docs/handbook/Introduction/_category_.json
  docs/handbook/Introduction/blog.md
  docs/handbook/amplitude-basics/_category_.json
  docs/handbook/google-analytics-basics/_category_.json
  docs/handbook/outro.md
  docs/handbook/tutorial-basics/_category_.json
  docs/handbook/tutorial-extras/_category_.json
  docs/handbook/tutorial-extras/which-data-should-be-tracked-blog.md
Labels: 📚 핸드북
